import { Prompt } from "./d1-client.js";

export interface LanguageConfig {
  code: string;
  name: string;
  readmeFileName: string;
}

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  { code: "en", name: "English", readmeFileName: "README.md" },
  { code: "zh", name: "简体中文", readmeFileName: "README_zh.md" },
];

const MAX_PROMPTS_TO_DISPLAY = 100;
const APP_HOME_URL = "https://prompthub.gokuscraper.com";

const en = {
  title: "SeedDance 2 Prompts",
  viewInGallery: "View in Web Gallery",
  browseGallery: "👉 Browse on Goku Prompt Hub",
  galleryFeatures: "Why use our gallery?",
  subtitle: "A curated collection of creative prompts for SeedDance 2",

  stats: "Statistics",
  totalPrompts: "Total Prompts",
  lastUpdated: "Last Updated",
  metric: "Metric",
  count: "Count",
  description: "Description",
  prompt: "Prompt",
  generatedVideos: "Generated Videos (Click to play ↗)",
  details: "Details",
  author: "Author",
  source: "Source",
  published: "Published",
  tryItNow: "🐵 Try it on Goku Prompt Hub",
  allPrompts: "All Prompts",
  license: "License",
  licensedUnder: "Licensed under CC BY 4.0.",
  acknowledgements: "Acknowledgements",
  starHistory: "Star History",
  autoGenerated: "This README is automatically generated. Last updated:",
  starRepo: "Star this repo",
  visualLayout: "Visual Layout",
  search: "Search",
  mobile: "Mobile",
  aiGenerate: "AI One-Click Generation",
  categories: "Categories",
  githubReadme: "GitHub README",
  youmindGallery: "Goku Prompt Hub",
  linearList: "Linear list",
  masonryGrid: "Beautiful Masonry Grid",
  ctrlFOnly: "Ctrl+F only",
  fullTextSearch: "Full-text search with filters",
  basic: "Basic",
  fullyResponsive: "Fully responsive",
  aiOneClickGen: "AI one-click generation",
  categoryBrowsing: "Category browsing",
  moreNotShown: "More Prompts Not Shown",
  limitNote: "Due to GitHub's content length limitations, we can only display the first",
  limitNoteEnd: "prompts in this README.",
  dataset: "HuggingFace Dataset",
  datasetDownload: "Download Dataset",
  datasetDesc1: "Contains",
  datasetDesc2: "+ SeedDance 2 prompts and generated images, suitable for batch analysis and secondary creation.",
};

const zh: typeof en = {
  title: "SeedDance 2 提示词精选",
  viewInGallery: "在网页图库中查看",
  browseGallery: "👉 浏览悟空提示词 Hub 图库",
  galleryFeatures: "为什么使用图库？",
  subtitle: "SeedDance 2 创意提示词精选集合",

  stats: "统计数据",
  totalPrompts: "提示词总数",
  lastUpdated: "最后更新",
  metric: "指标",
  count: "数量",
  description: "描述",
  prompt: "提示词",
  generatedVideos: "生成视频（点击播放 ↗）",
  details: "详情",
  author: "作者",
  source: "来源",
  published: "发布时间",
  tryItNow: "🐵 在悟空提示词 Hub 中查看",
  allPrompts: "所有提示词",
  license: "许可证",
  licensedUnder: "根据 CC BY 4.0 许可。",
  acknowledgements: "致谢",
  starHistory: "Star 历史",
  autoGenerated: "此 README 自动生成。最后更新：",
  starRepo: "给仓库点星",
  visualLayout: "可视化布局",
  search: "搜索",
  mobile: "移动端",
  aiGenerate: "AI 一键生图",
  categories: "分类",
  githubReadme: "GitHub README",
  youmindGallery: "悟空提示词 Hub",
  linearList: "线性列表",
  masonryGrid: "精美的瀑布流网格",
  ctrlFOnly: "仅 Ctrl+F",
  fullTextSearch: "全文搜索和筛选",
  basic: "基础",
  fullyResponsive: "完全响应式",
  aiOneClickGen: "AI 一键生图",
  categoryBrowsing: "分类浏览",
  moreNotShown: "更多提示词未显示",
  limitNote: "由于 GitHub 内容长度限制，本 README 仅显示前",
  limitNoteEnd: "条提示词。",
  dataset: "HuggingFace 数据集",
  datasetDownload: "下载数据集",
  datasetDesc1: "包含",
  datasetDesc2: "+ 条 SeedDance 2 提示词及其生成图片，适合批量分析和二次创作。",
};

const translations: Record<string, typeof en> = { en, zh };
const t = (key: keyof typeof en, locale: string): string => {
  const lang = translations[locale] || en;
  return lang[key] ?? en[key];
};

function cleanPromptContent(content: string): string {
  if (!content) return content;
  let cleaned = content;
  cleaned = cleaned.replace(/^```[\w-]*\s*\n?/im, "");
  cleaned = cleaned.replace(/\n?```\s*$/im, "");
  cleaned = cleaned.replace(/\n```[\w-]*\s*\n/g, "\n");
  cleaned = cleaned.trim();
  return cleaned;
}

function generateLanguageNav(currentLocale: string): string {
  const badges = SUPPORTED_LANGUAGES.map((lang) => {
    const isCurrent = lang.code === currentLocale;
    const color = isCurrent ? "brightgreen" : "lightgrey";
    const text = isCurrent ? "Current" : "Click%20to%20View";
    const link = lang.readmeFileName;
    const safeName = encodeURIComponent(lang.name);
    return `[![${lang.name}](https://img.shields.io/badge/${safeName}-${text}-${color})](${link})`;
  });

  return badges.join(" ") + "\n\n";
}

export function generateMarkdown(
  prompts: Prompt[],
  total: number,
  locale: string = "en"
): string {
  const displayed = prompts.slice(0, MAX_PROMPTS_TO_DISPLAY);
  const hiddenCount = total - displayed.length;

  let md = generateHeader(locale);
  md += generateGalleryPreview(locale);
  md += generateDatasetSection(total, locale);
  md += generateStats(total, locale);
  md += generatePromptList(displayed, locale);
  md += generateFooter(hiddenCount, locale);

  return md;
}

function generateHeader(locale: string): string {
  return `
<a href="${APP_HOME_URL}">
  <img src="banner.png" alt="Goku Prompt Hub" width="100%" />
</a>

# 🚀 ${t("title", locale)}

> 🎨 ${t("subtitle", locale)}

${generateLanguageNav(locale)}

`;
}

function generateGalleryPreview(locale: string): string {
  return `## 🌐 ${t("viewInGallery", locale)}

<div align="center">

[![Gallery Preview](public/images/gallery-preview.jpg)](${APP_HOME_URL})

</div>

**[${t("browseGallery", locale)}](${APP_HOME_URL})**

${t("galleryFeatures", locale)}

| Feature | ${t("githubReadme", locale)} | ${t("youmindGallery", locale)} |
|---------|--------------|---------------------|
| 🎨 ${t("visualLayout", locale)} | ${t("linearList", locale)} | ${t("masonryGrid", locale)} |
| 🔍 ${t("search", locale)} | ${t("ctrlFOnly", locale)} | ${t("fullTextSearch", locale)} |
| 🤖 ${t("aiGenerate", locale)} | - | ${t("aiOneClickGen", locale)} |
| 📱 ${t("mobile", locale)} | ${t("basic", locale)} | ${t("fullyResponsive", locale)} |
| 🏷️ ${t("categories", locale)} | - | ${t("categoryBrowsing", locale)} |

---
`;
}

const HF_DATASET_URL =
  "https://huggingface.co/datasets/GokuScraper/seedance-2-prompts-datasets";

function generateDatasetSection(total: number, locale: string): string {
  const formatted = new Intl.NumberFormat(locale === "zh" ? "zh-CN" : "en").format(total);
  return `## 💾 ${t("dataset", locale)}

<div align="center">

[![🤗 HuggingFace](https://img.shields.io/badge/${encodeURIComponent("🤗 HuggingFace")}-${encodeURIComponent(t("datasetDownload", locale))}-blue)](${HF_DATASET_URL})

</div>

${t("datasetDesc1", locale)} ${formatted}${t("datasetDesc2", locale)}

---
`;
}

function generateStats(total: number, locale: string): string {
  const now = new Date().toLocaleString(locale, {
    timeZone: "UTC",
    dateStyle: "full",
    timeStyle: "long",
  });

  return `## 📊 ${t("stats", locale)}

<div align="center">

| ${t("metric", locale)} | ${t("count", locale)} |
|--------|-------|
| 📝 ${t("totalPrompts", locale)} | **${total}** |
| 🔄 ${t("lastUpdated", locale)} | **${now}** |

</div>

---
`;
}

function generatePromptSection(
  prompt: Prompt,
  index: number,
  locale: string
): string {
  const rawContent = prompt.content || prompt.translatedContent;
  const promptContent = cleanPromptContent(rawContent);
  const hasArguments = promptContent.includes("{argument");

  let md = `### No. ${index + 1}: ${prompt.title}\n\n`;

  md += `![Language-${prompt.language.toUpperCase()}](https://img.shields.io/badge/Language-${prompt.language.toUpperCase()}-blue)\n`;

  if (prompt.featured) {
    md += `![Featured](https://img.shields.io/badge/⭐-Featured-gold)\n`;
  }

  md += `\n#### 📖 ${t("description", locale)}\n\n${prompt.description}\n\n`;
  md += `#### 📝 ${t("prompt", locale)}\n\n\`\`\`\n${promptContent}\n\`\`\`\n\n`;

  if (prompt.video) {
    md += `#### 🎬 ${t("generatedVideos", locale)}\n\n`;
    md += `<div align="center">\n`;
    md += `<a href="${prompt.video}" target="_blank" rel="noreferrer">\n`;
    md += `  <img src="${prompt.poster || prompt.video}" width="600" alt="${prompt.title}" style="cursor:pointer">\n`;
    md += `</a>\n`;
    md += `</div>\n\n`;
  }

  md += `**[${t("tryItNow", locale)}](${APP_HOME_URL})**\n\n`;
  md += `---\n\n`;

  return md;
}

function generatePromptList(prompts: Prompt[], locale: string): string {
  if (prompts.length === 0) return "";

  let md = `## 📋 ${t("allPrompts", locale)}\n\n`;

  prompts.forEach((prompt, index) => {
    md += generatePromptSection(prompt, index, locale);
  });

  return md;
}

function generateFooter(hiddenCount: number, locale: string): string {
  const now = new Date().toLocaleString(locale, {
    timeZone: "UTC",
    dateStyle: "full",
    timeStyle: "long",
  });

  let md = "";

  if (hiddenCount > 0) {
    md += `## 📚 ${hiddenCount} ${t("moreNotShown", locale)}\n\n`;
    md += `<div align="center">\n\n`;
    md += `${t("limitNote", locale)} ${MAX_PROMPTS_TO_DISPLAY} ${t("limitNoteEnd", locale)}\n\n`;
    md += `**[👉 ${t("viewInGallery", locale)}](${APP_HOME_URL})**\n\n`;
    md += `</div>\n\n`;
  }

  md += `---\n\n`;
  md += `## 📄 ${t("license", locale)}\n\n`;
  md += `${t("licensedUnder", locale)}\n\n`;
  md += `---\n\n`;
  md += `## 🙏 ${t("acknowledgements", locale)}\n\n`;
  md += `- [Goku Prompt Hub](https://prompthub.gokuscraper.com)\n\n`;
  md += `---\n\n`;
  md += `<div align="center">\n\n`;
  md += `**[🌐 ${t("viewInGallery", locale)}](${APP_HOME_URL})** • `;
  md += `**[⭐ ${t("starRepo", locale)}](https://github.com/goku-open/awesome-seedance-2-prompts)**\n\n`;
  md += `<sub>🤖 ${t("autoGenerated", locale)} ${now}</sub>\n\n`;
  md += `</div>\n`;

  return md;
}
